/**
 * server.js — Express backend for the Curalink RAG assistant.
 *
 * Endpoints:
 *   POST /api/ask   – accepts { question }, retrieves relevant chunks via
 *                     cosine similarity, builds a grounded prompt, and streams
 *                     the Gemini response back as Server-Sent Events (SSE).
 */

require("dotenv").config();
const express = require("express");
const cors = require("cors");
const mongoose = require("mongoose");
const { GoogleGenerativeAI } = require("@google/generative-ai");

// ─── Config ────────────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3001;
const MONGO_URI = process.env.MONGO_URI || "mongodb://127.0.0.1:27017/curalink";
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const TOP_K = 5; // number of chunks to retrieve
const MAX_CONTEXT_CHARS = 6000; // cap on total context sent to the model

const MEDICAL_DISCLAIMER =
  "\n\n---\n⚠️ **Medical Disclaimer:** This information is generated by an AI " +
  "assistant for research purposes only. It does NOT constitute medical advice, " +
  "diagnosis, or treatment. Always consult a qualified healthcare professional " +
  "for clinical decisions.";

if (!GEMINI_API_KEY) {
  console.error("❌  GEMINI_API_KEY is not set.");
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);

// ─── Mongoose model (must match seed.js) ───────────────────────────────────────
const chunkSchema = new mongoose.Schema({
  text: String,
  embedding: [Number],
  title: String,
  pmid: String,
});

const Chunk = mongoose.model("Chunk", chunkSchema);

// ─── Retrieval helpers ─────────────────────────────────────────────────────────

/**
 * Cosine similarity between two vectors a and b.
 *
 *              Σ(a_i · b_i)
 *   cos(θ) = ──────────────────
 *            ||a|| · ||b||
 *
 * Returns a value in [-1, 1]; higher means more similar.
 */
function cosineSimilarity(a, b) {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

/**
 * Embed a text string using Gemini text-embedding-004.
 */
async function embedText(text) {
  const model = genAI.getGenerativeModel({ model: "text-embedding-004" });
  const result = await model.embedContent(text);
  return result.embedding.values;
}

/**
 * Retrieve the top-K most relevant chunks for a given query.
 *
 * Strategy (in-Node cosine similarity):
 *  1. Embed the query with text-embedding-004.
 *  2. Load ALL chunk documents from MongoDB (with embeddings).
 *  3. Score each chunk by cosine similarity against the query embedding.
 *  4. Sort descending and return the top-K results.
 *
 * This avoids any Atlas Vector Search dependency — it works with a plain
 * local mongod or any free Mongo cluster.
 */
async function retrieveChunks(query) {
  const queryEmbedding = await embedText(query);
  const allChunks = await Chunk.find({}).lean();

  const scored = allChunks.map((chunk) => ({
    ...chunk,
    score: cosineSimilarity(queryEmbedding, chunk.embedding),
  }));

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, TOP_K);
}

// ─── Prompt building ───────────────────────────────────────────────────────────

/**
 * Build the full prompt for Gemini.
 *
 * Structure:
 *  - System instructions (role, citation rules, disclaimer)
 *  - Retrieved context chunks (each labelled with title + PMID)
 *  - The user's question
 *
 * A character cap (MAX_CONTEXT_CHARS) is enforced on the context section
 * to keep the prompt small and within token limits.
 */
function buildPrompt(question, chunks) {
  // Build context block from retrieved chunks, respecting the character cap
  let contextBlock = "";
  const usedSources = [];

  for (const chunk of chunks) {
    const entry = `\n[Source: "${chunk.title}" — PMID: ${chunk.pmid}]\n${chunk.text}\n`;
    if (contextBlock.length + entry.length > MAX_CONTEXT_CHARS) break;
    contextBlock += entry;
    // Track unique sources
    if (!usedSources.find((s) => s.pmid === chunk.pmid)) {
      usedSources.push({ title: chunk.title, pmid: chunk.pmid, score: chunk.score });
    }
  }

  const prompt = `You are Curalink, a medical research assistant. Answer the user's question using ONLY the provided research abstracts below. Follow these rules strictly:

1. Base your answer ONLY on the provided sources. Do not use outside knowledge.
2. Cite sources inline using the format (PMID: XXXXXXXX) after each claim.
3. If the sources do not contain enough information to answer, say so clearly.
4. Do NOT provide personalized clinical advice or treatment recommendations.
5. Use clear, concise academic language accessible to researchers and clinicians.

--- RETRIEVED RESEARCH CONTEXT ---
${contextBlock}
--- END CONTEXT ---

User Question: ${question}

Answer:`;

  return { prompt, usedSources };
}

// ─── Express app ───────────────────────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json());

/**
 * POST /api/ask
 *
 * Request body: { "question": "..." }
 *
 * Response: Server-Sent Events stream.
 * Events:
 *   - type "chunk"   → { text: "..." }        (incremental answer tokens)
 *   - type "sources" → { sources: [...] }      (cited source list)
 *   - type "done"    → {}                       (stream complete)
 *   - type "error"   → { message: "..." }       (on failure)
 */
app.post("/api/ask", async (req, res) => {
  const { question } = req.body;

  if (!question || typeof question !== "string" || question.trim().length === 0) {
    return res.status(400).json({ error: "A non-empty 'question' field is required." });
  }

  // Set up SSE headers
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();

  const send = (type, data = {}) => {
    res.write(`data: ${JSON.stringify({ type, ...data })}\n\n`);
  };

  try {
    // 1. Retrieve relevant chunks
    const topChunks = await retrieveChunks(question.trim());

    // 2. Build the grounded prompt
    const { prompt, usedSources } = buildPrompt(question.trim(), topChunks);

    // 3. Send sources early so the client can render them while streaming
    send("sources", { sources: usedSources });

    // 4. Stream the Gemini response
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const result = await model.generateContentStream(prompt);

    for await (const chunk of result.stream) {
      const text = chunk.text();
      if (text) {
        send("chunk", { text });
      }
    }

    // 5. Append the medical disclaimer as a final chunk
    send("chunk", { text: MEDICAL_DISCLAIMER });
    send("done");
  } catch (err) {
    console.error("❌  /api/ask error:", err);
    send("error", { message: err.message || "Internal server error" });
  } finally {
    res.end();
  }
});

// Health check
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", service: "curalink" });
});

// ─── Start ─────────────────────────────────────────────────────────────────────
async function start() {
  console.log("🔌  Connecting to MongoDB…");
  await mongoose.connect(MONGO_URI);
  console.log("✅  Connected to MongoDB");

  app.listen(PORT, () => {
    console.log(`🚀  Curalink API running on http://localhost:${PORT}`);
  });
}

start().catch((err) => {
  console.error("❌  Failed to start server:", err);
  process.exit(1);
});
