/**
 * server.js — Curalink Express Backend v2
 *
 * ALL 5 PHASES INTEGRATED:
 *   Phase 1: Token efficiency — hash-based dedup in seed/upload, token-budgeted context
 *   Phase 2: Premium UI support — snippet field in sources response
 *   Phase 3: Multi-turn session memory — history injection + auto-summarization
 *   Phase 4: PDF/text upload — /api/upload route (see routes/upload.js)
 *   Phase 5: Anti-hallucination — PMID citation cross-check, validation SSE event
 *
 * SSE Event Types (POST /api/ask response):
 *   "sources"    → { sources: [...] }          — sent before generation starts
 *   "chunk"      → { text: "..." }             — incremental answer tokens
 *   "validation" → { valid, invalid, uncited }  — citation verification result
 *   "done"       → {}                           — stream complete
 *   "error"      → { message: "..." }           — on failure
 */

require("dotenv").config();
const express  = require("express");
const cors     = require("cors");
const mongoose = require("mongoose");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const Chunk   = require("./models/Chunk");
const Session = require("./models/Session");

// ─── Config ───────────────────────────────────────────────────────────────────
const PORT           = process.env.PORT   || 3001;
const MONGO_URI      = process.env.MONGO_URI || "mongodb://127.0.0.1:27017/curalink";
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

const TOP_K = 5;

// TOKEN EFFICIENCY: Instead of a naive char count, we budget by estimated tokens.
// Gemini models tokenize roughly 1 token per 4 characters.
// We allocate 2000 tokens (~8000 chars) for context — well within the model limit
// while allowing richer retrieval than the old 6000-char cap.
const CHARS_PER_TOKEN    = 4;
const CONTEXT_TOKEN_BUDGET = 2000;
const MAX_CONTEXT_CHARS  = CONTEXT_TOKEN_BUDGET * CHARS_PER_TOKEN; // 8000 chars

// Conversation memory settings
const HISTORY_WINDOW        = 4;  // last N messages injected verbatim
const SUMMARIZE_THRESHOLD   = 10; // summarize when session exceeds this many messages

// Regex for extracting cited PMIDs from the model's answer
const PMID_REGEX = /\(PMID:\s*(\d+)\)/g;

const MEDICAL_DISCLAIMER =
  "\n\n---\n⚠️ **Medical Disclaimer:** This information is generated by an AI " +
  "assistant for research purposes only. It does NOT constitute medical advice, " +
  "diagnosis, or treatment. Always consult a qualified healthcare professional " +
  "for clinical decisions.";

if (!GEMINI_API_KEY) {
  console.error("❌  GEMINI_API_KEY is not set.");
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);

// ─── Retrieval helpers ────────────────────────────────────────────────────────

/**
 * Cosine similarity between two equal-length vectors.
 *          Σ(a_i · b_i)
 * cos(θ) = ─────────────────
 *          ||a|| · ||b||
 */
function cosineSimilarity(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

/**
 * Embed a query string with Gemini text-embedding-001.
 * This is the ONE embedding API call per user question — unavoidable.
 */
async function embedText(text) {
  const model  = genAI.getGenerativeModel({ model: "gemini-embedding-001" });
  const result = await model.embedContent(text);
  return result.embedding.values;
}

/**
 * Find the top-K most relevant chunks for a query using in-memory cosine similarity.
 *
 * NOTE: Embeddings are pre-computed and stored in MongoDB.
 * We only call the Gemini API once (to embed the query), never to re-embed chunks.
 */
async function retrieveChunks(query) {
  const queryEmbedding = await embedText(query);

  // Load only the fields needed — excludes timestamps/createdAt to reduce payload
  const allChunks = await Chunk.find({})
    .select("text embedding title pmid source documentId")
    .lean();

  const scored = allChunks.map((chunk) => ({
    ...chunk,
    score: cosineSimilarity(queryEmbedding, chunk.embedding),
  }));

  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, TOP_K);
}

// ─── Prompt builder ───────────────────────────────────────────────────────────

/**
 * Build the RAG prompt with optional conversation history context.
 *
 * Token strategy:
 *   - Context block capped at MAX_CONTEXT_CHARS (token-budget-aware)
 *   - History block uses only the last HISTORY_WINDOW messages verbatim
 *   - Older history is replaced by session.summary (generated by Gemini flash, cheap)
 */
function buildPrompt(question, chunks, session) {
  // ── 1. Context block ──────────────────────────────────────────────────────
  let contextBlock = "";
  let contextChars = 0;
  const usedSources = [];

  for (const chunk of chunks) {
    const entry = `\n[Source: "${chunk.title}" — PMID: ${chunk.pmid}]\n${chunk.text}\n`;
    if (contextChars + entry.length > MAX_CONTEXT_CHARS) break;
    contextBlock += entry;
    contextChars += entry.length;

    // Collect unique sources with snippet for client display
    if (!usedSources.find((s) => s.pmid === chunk.pmid)) {
      usedSources.push({
        title:      chunk.title,
        pmid:       chunk.pmid,
        score:      Math.round(chunk.score * 1000) / 1000,
        source:     chunk.source || "seed",
        documentId: chunk.documentId || null,
        snippet:    chunk.text.slice(0, 350), // shown in source card expand
      });
    }
  }

  // ── 2. History block ──────────────────────────────────────────────────────
  let historyBlock = "";
  if (session) {
    if (session.summary) {
      historyBlock += `[Conversation Background]\n${session.summary}\n\n`;
    }
    const msgs = (session.messages || []).slice(-HISTORY_WINDOW);
    if (msgs.length > 0) {
      historyBlock += "[Recent Conversation]\n";
      for (const msg of msgs) {
        const role = msg.role === "user" ? "User" : "Assistant";
        // Trim assistant messages to keep history compact
        const content =
          msg.role === "assistant" && msg.content.length > 600
            ? msg.content.slice(0, 600) + "…"
            : msg.content;
        historyBlock += `${role}: ${content}\n`;
      }
      historyBlock += "\n";
    }
  }

  // ── 3. Assemble prompt ────────────────────────────────────────────────────
  const prompt = `You are Curalink, a medical research assistant. Answer the user's question using ONLY the provided research abstracts below. Follow these rules strictly:

1. Base your answer ONLY on the provided sources. Do not use outside knowledge.
2. Cite sources inline using the format (PMID: XXXXXXXX) after each claim.
3. If the sources do not contain enough information to answer, say so clearly.
4. Do NOT provide personalized clinical advice or treatment recommendations.
5. Use clear, concise academic language accessible to researchers and clinicians.
6. When the question refers to prior conversation, maintain continuity and context.
${historyBlock ? historyBlock : ""}
--- RETRIEVED RESEARCH CONTEXT ---
${contextBlock}
--- END CONTEXT ---

User Question: ${question}

Answer:`;

  return { prompt, usedSources };
}

// ─── Anti-hallucination validator ─────────────────────────────────────────────

/**
 * Parse all (PMID: XXXXXXXX) citations in the answer and cross-check them
 * against the list of actually retrieved sources.
 *
 * Returns:
 *   valid   — PMIDs that are both cited AND in usedSources ✅
 *   invalid — PMIDs cited but NOT in usedSources (hallucination!) 🚫
 *   uncited — PMIDs in usedSources but never cited in the answer ⚠️
 */
function validateCitations(answer, usedSources) {
  const matches    = [...answer.matchAll(PMID_REGEX)];
  const cited      = [...new Set(matches.map((m) => m[1]))];
  const sourcePmids = usedSources.map((s) => s.pmid);

  return {
    valid:   cited.filter((p) => sourcePmids.includes(p)),
    invalid: cited.filter((p) => !sourcePmids.includes(p)),
    uncited: sourcePmids.filter((p) => !cited.includes(p)),
  };
}

// ─── Session history management ───────────────────────────────────────────────

/**
 * If the session has grown too long, summarize older messages with a cheap
 * Gemini flash call and trim them from the session, keeping context tight.
 *
 * This is how we prevent the conversation history from consuming too many
 * tokens in the RAG prompt over time.
 */
async function maybeSummarizeSession(session) {
  if (!session || session.messages.length <= SUMMARIZE_THRESHOLD) return;

  const toSummarize = session.messages.slice(0, -HISTORY_WINDOW);
  if (toSummarize.length === 0) return;

  const histText = toSummarize
    .map((m) => `${m.role === "user" ? "User" : "Assistant"}: ${m.content.slice(0, 400)}`)
    .join("\n");

  const summaryPrompt =
    `Summarize this medical research conversation in 2-3 concise sentences, ` +
    `focusing on key topics, questions asked, and findings discussed:\n\n${histText}`;

  try {
    const model  = genAI.getGenerativeModel({ model: "gemini-3.5-flash" });
    const result = await model.generateContent(summaryPrompt);
    session.summary  = result.response.text();
    session.messages = session.messages.slice(-HISTORY_WINDOW);
    await session.save();
    console.log("📝  Session history summarized and trimmed.");
  } catch (err) {
    console.warn("⚠️  History summarization failed (non-critical):", err.message);
  }
}

// ─── Express app ──────────────────────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json({ limit: "2mb" }));

// Mount upload route (Phase 4)
const uploadRouter = require("./routes/upload")(genAI);
app.use("/api/upload", uploadRouter);

// ─── Session Endpoints (Phase 3) ──────────────────────────────────────────────

/** GET /api/sessions — list sessions (metadata only, no messages) */
app.get("/api/sessions", async (_req, res) => {
  try {
    const sessions = await Session.find({})
      .select("sessionId title createdAt updatedAt")
      .sort({ updatedAt: -1 })
      .lean();
    res.json({ sessions });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/** POST /api/sessions — create a new empty session */
app.post("/api/sessions", async (_req, res) => {
  try {
    const session = await Session.create({});
    res.json({ sessionId: session.sessionId, title: session.title });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/** GET /api/sessions/:id — get full session with all messages */
app.get("/api/sessions/:id", async (req, res) => {
  try {
    const session = await Session.findOne({ sessionId: req.params.id }).lean();
    if (!session) return res.status(404).json({ error: "Session not found." });
    res.json(session);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/** DELETE /api/sessions/:id */
app.delete("/api/sessions/:id", async (req, res) => {
  try {
    await Session.deleteOne({ sessionId: req.params.id });
    res.json({ ok: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

/** GET /api/documents — list uploaded documents */
app.get("/api/documents", async (_req, res) => {
  try {
    const docs = await Chunk.aggregate([
      { $match: { source: "upload", documentId: { $ne: null } } },
      { $group: {
        _id:    "$documentId",
        title:  { $first: "$title" },
        pmid:   { $first: "$pmid" },
        chunks: { $sum: 1 },
      }},
      { $sort: { _id: -1 } },
    ]);
    res.json({ documents: docs });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ─── Main RAG Endpoint ────────────────────────────────────────────────────────

/**
 * POST /api/ask
 *
 * Body: { question: string, sessionId?: string }
 *
 * SSE stream events in order:
 *   1. "sources"    — retrieved source list (sent before generation for instant display)
 *   2. "chunk"      — token-by-token answer text
 *   3. "validation" — citation verification result (sent after full answer received)
 *   4. "chunk"      — medical disclaimer appended
 *   5. "done"       — stream complete
 */
app.post("/api/ask", async (req, res) => {
  const { question, sessionId } = req.body;

  if (!question || typeof question !== "string" || question.trim().length === 0) {
    return res.status(400).json({ error: "A non-empty 'question' field is required." });
  }

  // Set up SSE headers
  res.setHeader("Content-Type",  "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection",    "keep-alive");
  res.flushHeaders();

  const send = (type, data = {}) => {
    res.write(`data: ${JSON.stringify({ type, ...data })}\n\n`);
  };

  try {
    // ── 1. Load session (Phase 3) ─────────────────────────────────────────
    let session = null;
    if (sessionId) {
      session = await Session.findOne({ sessionId });
      if (session) {
        // Compress old history if needed to keep context tight
        await maybeSummarizeSession(session);
      }
    }

    // ── 2. Retrieve top-K relevant chunks (ONE embed API call) ─────────────
    const topChunks = await retrieveChunks(question.trim());

    // ── 3. Build grounded prompt ───────────────────────────────────────────
    const { prompt, usedSources } = buildPrompt(question.trim(), topChunks, session);

    // ── 4. Send sources immediately (client renders them while streaming) ──
    send("sources", { sources: usedSources });

    // ── 5. Stream the Gemini response (accumulate for validation) ──────────
    let fullAnswer = "";
    const model  = genAI.getGenerativeModel({ model: "gemini-3.5-flash" });
    const result = await model.generateContentStream(prompt);

    for await (const chunk of result.stream) {
      const text = chunk.text();
      if (text) {
        send("chunk", { text });
        fullAnswer += text;
      }
    }

    // ── 6. Anti-hallucination validation (Phase 5) ─────────────────────────
    const validation = validateCitations(fullAnswer, usedSources);
    send("validation", validation);

    // ── 7. Append disclaimer and finish ───────────────────────────────────
    send("chunk", { text: MEDICAL_DISCLAIMER });
    send("done");

    // ── 8. Persist to session (Phase 3) ───────────────────────────────────
    if (session) {
      const fullContent = fullAnswer + MEDICAL_DISCLAIMER;

      session.messages.push({ role: "user", content: question.trim() });
      session.messages.push({
        role:       "assistant",
        content:    fullContent,
        sources:    usedSources,
        validation,
      });

      // Auto-title session from the first question asked
      if (session.messages.length === 2) {
        const q = question.trim();
        session.title = q.length > 60 ? q.slice(0, 60) + "…" : q;
      }

      session.markModified("messages");
      await session.save();
    }

  } catch (err) {
    console.error("❌  /api/ask error:", err);
    send("error", { message: err.message || "Internal server error." });
  } finally {
    res.end();
  }
});

// ─── Health check ─────────────────────────────────────────────────────────────
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", service: "curalink-v2", timestamp: new Date().toISOString() });
});

// ─── Start ────────────────────────────────────────────────────────────────────
async function start() {
  console.log("🔌  Connecting to MongoDB…");
  await mongoose.connect(MONGO_URI);
  console.log("✅  Connected to MongoDB");
  app.listen(PORT, () => {
    console.log(`🚀  Curalink v2 running on http://localhost:${PORT}`);
    console.log(`    ↳ All 5 phases active: caching · sessions · upload · validation · premium-ui`);
  });
}

start().catch((err) => {
  console.error("❌  Failed to start server:", err);
  process.exit(1);
});
